/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface L3TokenBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridgeToL1"
      | "counterpartBridge"
      | "finalizeBridgeFromL1"
      | "owner"
      | "processedHashes"
      | "setCounterpartBridge"
      | "token"
      | "withdrawETH"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgedFromL1"
      | "BridgedToL1"
      | "CounterpartBridgeSet"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bridgeToL1",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "counterpartBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeBridgeFromL1",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCounterpartBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bridgeToL1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "counterpartBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeBridgeFromL1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCounterpartBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
}

export namespace BridgedFromL1Event {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    nonce: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    nonce: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    nonce: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgedToL1Event {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    nonce: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    nonce: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    nonce: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CounterpartBridgeSetEvent {
  export type InputTuple = [newBridge: AddressLike];
  export type OutputTuple = [newBridge: string];
  export interface OutputObject {
    newBridge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface L3TokenBridge extends BaseContract {
  connect(runner?: ContractRunner | null): L3TokenBridge;
  waitForDeployment(): Promise<this>;

  interface: L3TokenBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgeToL1: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  counterpartBridge: TypedContractMethod<[], [string], "view">;

  finalizeBridgeFromL1: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, nonce: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processedHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  setCounterpartBridge: TypedContractMethod<
    [_counterpartBridge: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  withdrawETH: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgeToL1"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "counterpartBridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeBridgeFromL1"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, nonce: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processedHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setCounterpartBridge"
  ): TypedContractMethod<
    [_counterpartBridge: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BridgedFromL1"
  ): TypedContractEvent<
    BridgedFromL1Event.InputTuple,
    BridgedFromL1Event.OutputTuple,
    BridgedFromL1Event.OutputObject
  >;
  getEvent(
    key: "BridgedToL1"
  ): TypedContractEvent<
    BridgedToL1Event.InputTuple,
    BridgedToL1Event.OutputTuple,
    BridgedToL1Event.OutputObject
  >;
  getEvent(
    key: "CounterpartBridgeSet"
  ): TypedContractEvent<
    CounterpartBridgeSetEvent.InputTuple,
    CounterpartBridgeSetEvent.OutputTuple,
    CounterpartBridgeSetEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "BridgedFromL1(address,address,uint256,bytes32)": TypedContractEvent<
      BridgedFromL1Event.InputTuple,
      BridgedFromL1Event.OutputTuple,
      BridgedFromL1Event.OutputObject
    >;
    BridgedFromL1: TypedContractEvent<
      BridgedFromL1Event.InputTuple,
      BridgedFromL1Event.OutputTuple,
      BridgedFromL1Event.OutputObject
    >;

    "BridgedToL1(address,address,uint256,bytes32)": TypedContractEvent<
      BridgedToL1Event.InputTuple,
      BridgedToL1Event.OutputTuple,
      BridgedToL1Event.OutputObject
    >;
    BridgedToL1: TypedContractEvent<
      BridgedToL1Event.InputTuple,
      BridgedToL1Event.OutputTuple,
      BridgedToL1Event.OutputObject
    >;

    "CounterpartBridgeSet(address)": TypedContractEvent<
      CounterpartBridgeSetEvent.InputTuple,
      CounterpartBridgeSetEvent.OutputTuple,
      CounterpartBridgeSetEvent.OutputObject
    >;
    CounterpartBridgeSet: TypedContractEvent<
      CounterpartBridgeSetEvent.InputTuple,
      CounterpartBridgeSetEvent.OutputTuple,
      CounterpartBridgeSetEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
